
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 05 00:17:57 CET 2010
//----------------------------------------------------

package org.fantomery.ttinterpreter.ttlangs.tfl;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SELECT_QUESTION = 78;
  public static final int IPINF = 61;
  public static final int LEFT = 26;
  public static final int TIMES = 51;
  public static final int PATH = 17;
  public static final int PATH_PARENT = 69;
  public static final int RIGHT = 27;
  public static final int POINT_CHILD = 68;
  public static final int SEMI = 3;
  public static final int LPOINT_AND_RPOINT = 77;
  public static final int COMMA = 2;
  public static final int RBRACE = 8;
  public static final int PATH_CHILD = 67;
  public static final int JOIN = 65;
  public static final int TIMES_ASSIGN = 33;
  public static final int RPAREN = 6;
  public static final int VERTEX = 12;
  public static final int RMINF = 62;
  public static final int LBRACE = 7;
  public static final int POINT_AND_POINT = 74;
  public static final int LPAREN = 5;
  public static final int CHILD = 25;
  public static final int FALSE = 42;
  public static final int DESTROY = 16;
  public static final int ELSEIF = 37;
  public static final int ARRAY = 19;
  public static final int VAR = 14;
  public static final int RPINF = 63;
  public static final int ALGORITHM = 11;
  public static final int MIN = 56;
  public static final int SELECT = 79;
  public static final int AMPERSAND_ASSIGN = 35;
  public static final int TRUE = 41;
  public static final int PLUS = 49;
  public static final int DIVIDE = 52;
  public static final int EXISTS = 57;
  public static final int DATA_TYPE = 20;
  public static final int EQUAL = 43;
  public static final int ASSIGN = 30;
  public static final int PATH_AND_PATH = 71;
  public static final int VARIABLE = 21;
  public static final int MINUS_ASSIGN = 32;
  public static final int GREATER = 46;
  public static final int MAX = 55;
  public static final int ELSE = 38;
  public static final int POINT = 18;
  public static final int I_NUMBER = 58;
  public static final int DOT = 4;
  public static final int AMPERSAND = 54;
  public static final int PATH_AND_POINT = 72;
  public static final int RPOINT_OVER_LPOINT = 76;
  public static final int LPOINT_OVER_RPOINT = 75;
  public static final int STRING_LITERAL = 64;
  public static final int EOF = 0;
  public static final int C = 24;
  public static final int B = 23;
  public static final int A = 22;
  public static final int DIVIDE_ASSIGN = 34;
  public static final int MINUS = 50;
  public static final int OR = 40;
  public static final int error = 1;
  public static final int NOT_EQUAL = 44;
  public static final int SPLIT = 66;
  public static final int IF = 36;
  public static final int GREATER_EQUAL = 48;
  public static final int PLUS_ASSIGN = 31;
  public static final int CLUSTER = 13;
  public static final int LESS_EQUAL = 47;
  public static final int CREATE = 15;
  public static final int R_NUMBER = 59;
  public static final int BORDER = 29;
  public static final int RBRACKET = 10;
  public static final int POINT_PARENT = 70;
  public static final int LESS = 45;
  public static final int POINT_AND_PATH = 73;
  public static final int IMINF = 60;
  public static final int AND = 39;
  public static final int UMINUS = 53;
  public static final int LBRACKET = 9;
  public static final int COMMON = 28;
}

