
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 11 21:11:30 CEST 2008
//----------------------------------------------------

package org.fantomery.ttinterpreter.ttlangs.tql;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXIT = 2;
  public static final int PLUS = 25;
  public static final int RBRACE = 8;
  public static final int RPAREN = 4;
  public static final int INFO = 22;
  public static final int SEMI = 9;
  public static final int CUT = 28;
  public static final int R = 24;
  public static final int VARIABLE = 29;
  public static final int TRUE = 18;
  public static final int L = 23;
  public static final int LPAREN = 3;
  public static final int LBRACKET = 5;
  public static final int LBRACE = 7;
  public static final int IPINF = 13;
  public static final int RBRACKET = 6;
  public static final int I_NUMBER = 14;
  public static final int STRING_LITERAL = 30;
  public static final int RMINF = 15;
  public static final int COMMA = 10;
  public static final int EOF = 0;
  public static final int EDGE = 21;
  public static final int LINK = 27;
  public static final int MINUS = 26;
  public static final int FALSE = 19;
  public static final int error = 1;
  public static final int ASSIGN = 11;
  public static final int R_NUMBER = 17;
  public static final int RPINF = 16;
  public static final int IMINF = 12;
  public static final int NODE = 20;
}

